#
ROOT: /compute/zoidberg/tartanair_v2
TYPE: tartanv2
DATASETS:
  [
    AbandonedSchool/Data_easy/P000,
    AbandonedSchool/Data_easy/P001,
    AbandonedSchool/Data_easy/P002,
    AbandonedSchool/Data_easy/P003,
    AbandonedSchool/Data_easy/P004,
    AbandonedSchool/Data_easy/P005,
    AbandonedSchool/Data_easy/P006,
    AbandonedSchool/Data_easy/P007,
    AbandonedSchool/Data_easy/P008,
    AbandonedSchool/Data_easy/P009,
    CoalMine/Data_easy/P000,
    CoalMine/Data_easy/P001,
    CoalMine/Data_easy/P002,
    CoalMine/Data_easy/P003,
    CoalMine/Data_easy/P004,
    CoalMine/Data_easy/P005,
    AbandonedSchool/Data_hard/P000,
    AbandonedSchool/Data_hard/P001,
    AbandonedSchool/Data_hard/P002,
    AbandonedSchool/Data_hard/P003,
    AbandonedSchool/Data_hard/P004,
    AbandonedSchool/Data_hard/P005,
    AbandonedSchool/Data_hard/P006,
    AbandonedSchool/Data_hard/P007,
    AbandonedSchool/Data_hard/P008,
    AbandonedSchool/Data_hard/P009,
    CoalMine/Data_hard/P000,
    CoalMine/Data_hard/P001,
    CoalMine/Data_hard/P002,
    CoalMine/Data_hard/P003,
    CoalMine/Data_hard/P004,
    CoalMine/Data_hard/P005,
  ]
VO_MODEL: ./models/stereo_cvt_tartanvo_1914.pkl
POSE_MODEL: null